language: c
sudo: required
dist: trusty
os:
  - linux
branches:
  except:
    - /^(wip\/)?(msvc|windows)(\-.+)?$/
env:
  matrix:
    - COMPILER=gcc-5 CFLAGS="-fsanitize=address -fsanitize=undefined"
    # This is disabled due to an issue with the packaging, not Âµnit.
    # - COMPILER=clang-3.7 CFLAGS="-fsanitize=address -fsanitize=undefined"
    - COMPILER=gcc-4.9 CFLAGS="-fsanitize=address -fsanitize=undefined"
    - COMPILER=clang-3.6 CFLAGS="-fsanitize=address -fsanitize=undefined"
    - COMPILER=gcc-4.8 CFLAGS="-fsanitize=address"
    - COMPILER=gcc-4.7
    - COMPILER=gcc-4.6
    - COMPILER=gcc-4.4
    - COMPILER=clang-3.5 CFLAGS="-fsanitize=address -fsanitize=undefined"
    - COMPILER=clang-3.4 CFLAGS="-fsanitize=address -fsanitize=undefined"
    - COMPILER=x86_64-w64-mingw32-gcc EXTENSION=".exe"
    - COMPILER=i686-w64-mingw32-gcc EXTENSION=".exe"
  global:
    - GLOBAL_CFLAGS="-std=c99 -g -fno-omit-frame-pointer -Wall -Wextra -Werror"
before_install:
 - ./.travis-install-compiler.sh
script:
 - make CC="${COMPILER}" CFLAGS="$GLOBAL_CFLAGS $CFLAGS" EXTENSION="$EXTENSION"
 # Installing Wine wants to pull in the graphical stack, so we can't
 # run the test for mingw.
 - if [ x"$EXTENSION" = "x" ]; then make test; fi
# notifications:
#   email: false
